services:
  pg:
    image: bitnami/postgresql:16.2.0
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/scripts:/etc/postgresql/scripts
    container_name: next-saas-bd
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}